apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hipster-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: frontend
    http:
      paths:
        - path: /
          backend:
            serviceName: frontend
            servicePort: 8080